# Generated by Django 3.2.2 on 2021-05-07 06:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cameras', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='camera',
            name='picture_url',
            field=models.URLField(default='/static/default.png'),
        ),
    ]
